
# logging:
#    config: classpath:logback.xml

spring:
  main:
    allow-bean-definition-overriding: true
    # none, servlet, reactive,
    web-application-type: servlet

  datasource_local:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: x
    driverClassName: org.postgresql.Driver

  #datasource_server:
  datasource:
    url: jdbc:postgresql://81.183.232.211:30001/postgres
    username: greenbull
    password: Tibi123!
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      #            dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: update
      #ddl-auto: create

springdoc:
  swagger-ui:
    path: "swagger.html"
    enabled: true
    tryItOutEnabled: true
    filter: true

app:
  security:
    #cross-origin: "*"
    cross-origin: "http://localhost:4200"

    jwt-secret: GreenBullSecretKey
    jwtExpirationMs: 86400000
    #jwtCookieName: GreenBullCookie

logging:
  level:
    org:
      springframework:
        security: DEBUG
